JDP210403-5
adrianpaz/project-jdp-2104-03 pull request #2
Opened 2021-04-28 14:13 UTC by Dalmonion

UserController - wstępna implementacja endpointów

2021-04-28 14:16 UTC, Dalmonion commented
CircleCI test nie przechodzi bo w requescie nie ma zawartego zaktualizowanego pliku build.gradle

2021-04-29 12:29 UTC, adrianpaz commented
To branch musi przechodzić, inaczej nie uda się zmergować :)

2021-04-29 16:03 UTC, adrianpaz requested changes
xcvxcv

2021-04-29 16:03 UTC, adrianpaz reviewed
xcvxcv

2021-04-30 10:25 UTC, dziadowicz commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +    public int generateKey() {
Klucz ma być generowany po podaniu danych użytkownika. Może warto zaimplementować wstępnie jakiś argument tej metodzie?

2021-04-30 11:14 UTC, Dalmonion commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +    public int generateKey() {
Poprawione :) wrzuciłem tam póki co pełen obiekt Dto usera

2021-04-30 14:24 UTC, adrianpaz approved these changes

2021-04-30 15:58 UTC, merged